# -*- coding: utf-8 -*-
"""cancelamento_git.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R1L5C-jPtxEc0DA8e0pCW4hQveQ7qUSx

# **Bibliotecas**
"""

from google.colab import drive
import pandas as pd
import re
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import os

"""# **CARREGAMENTO DOS ARQUIVOS**"""

# se for rodar localmente fora do Colab, você pode comentar a linha do drive.mount
drive.mount('/content/drive')

# definindo os caminhos dos arquivos Drive
path_pasta = './dados_ficticios/'

file_cancelamentos = path_pasta + 'cancelamentos_abril_fake.xlsx'
file_chamados = path_pasta + 'chamados_os_abril_fake.csv'

#lendo o CSV de chamados e definindo como os_historico para manter a consistência do script
chamados = pd.read_csv(file_chamados, sep=';', encoding='utf-8', engine='python')
os_historico = chamados

cancelamentos = pd.read_excel(file_cancelamentos)

print("--- ARQUIVOS CARREGADOS COM SUCESSO ---")
print(f"Total de Cancelados em Abril: {len(cancelamentos)}")
print(f"Total de O.S. no Histórico: {len(os_historico)}")

"""**TRATAMENTO DA BASE DE CANCELAMENTOS (ABRIL)**"""

# extrair o ID numérico do início da string
cancelamentos['ID_Sistema'] = cancelamentos['Cliente'].str.extract(r'^(\d+)').astype('Int64')

# separar o nome do cliente limpando o ID e o traço da frente
cancelamentos['Nome_Cliente'] = cancelamentos['Cliente'].str.replace(r'^\d+\s*-\s*', '', regex=True)

# trata o valor do plano: substitui a vírgula por ponto e converte para float
cancelamentos['Valor_Plano_Num'] = cancelamentos['Valor do Plano'].astype(str).str.replace(',', '.')
cancelamentos['Valor_Plano_Num'] = pd.to_numeric(cancelamentos['Valor_Plano_Num'], errors='coerce')

# ajustar as colunas de data que não estavam formatadas
cancelamentos['Data_Cancelamento_DT'] = pd.to_datetime(cancelamentos['Data Cancelamento'], format='%d/%m/%Y', errors='coerce')
cancelamentos['Data_Ativacao_DT'] = pd.to_datetime(cancelamentos['Data Ativação'], format='%d/%m/%Y', errors='coerce')

"""**TRATAMENTO E FILTRAGEM DO HISTÓRICO DE O.S. (JAN A ABR)**"""

# garantindo que a coluna ID - Cliente seja lida como numérico Int64 para o cruzamento
os_historico['ID_Cliente_Clean'] = pd.to_numeric(os_historico['ID - Cliente'], errors='coerce').astype('Int64')

# normalizar os textos dos assuntos para maiúsculas
os_historico['Assunto_Up'] = os_historico['Assunto'].astype(str).str.upper().str.strip()

# LISTA DE EXCLUSÃO: filtrar os procedimentos de rotina para isolar defeitos reais
os_ignoradas = [
    'RETIRADA DE EQUIPAMENTO', 'RETIRADA DE EQUIPAMENTOS',
    'ATIVAÇÃO INICIAL FIBRA ÓPTICA', 'VERIFICAR FIBRA - ATIVAÇÃO INICIAL',
    'ATIVAÇÃO INICIAL URBANA', 'TRANSFERÊNCIA DE ENDEREÇO',
    'PASSAGEM DE CABO DE REDE', 'TRANSFERÊNCIA DE ENDEREÇO - FIBRA'
]
os_ignoradas_norm = [item.upper() for item in os_ignoradas]

# contar estritamente as O.S. que indicam falhas técnicas ou manutenções
falhas_historicas = os_historico[~os_historico['Assunto_Up'].isin(os_ignoradas_norm)].copy()

"""**CRIAÇÃO DAS MÉTRICAS TÉCNICAS REAIS POR CLIENTE**"""

# Métrica A: total de ordens de serviço (visitas ao todo, incluindo rotinas) que o cliente gerou no ano
df_total_visitas = os_historico.groupby('ID_Cliente_Clean').size().reset_index(name='Total_Visitas_Tecnicas')

# Métrica B: quantidade de chamados estritamente de falhas/defeitos
df_qtd_falhas = falhas_historicas.groupby('ID_Cliente_Clean').size().reset_index(name='Qtd_Chamados_Defeito')

# Métrica C: qual foi a falha técnica principal (mais frequente) no histórico do cliente
df_falha_recorrente = (falhas_historicas.groupby('ID_Cliente_Clean')['Assunto']
                       .agg(lambda x: x.value_counts().index[0] if not x.empty else 'Sem falhas no histórico')
                       .reset_index(name='Historico_Defeito_Principal'))

"""**MASTER JOIN (União Estruturada)**"""

# unir tabelas de cancelados com as agregações de O.S. históricas baseadas no ID do Sistema
base_final = pd.merge(cancelamentos, df_total_visitas.rename(columns={'ID_Cliente_Clean': 'ID_Sistema'}), on='ID_Sistema', how='left')
base_final = pd.merge(base_final, df_qtd_falhas.rename(columns={'ID_Cliente_Clean': 'ID_Sistema'}), on='ID_Sistema', how='left')
base_final = pd.merge(base_final, df_falha_recorrente.rename(columns={'ID_Cliente_Clean': 'ID_Sistema'}), on='ID_Sistema', how='left')

# tratamento pós-join para preencher valores vazios (NaN) de quem nunca teve O.S.
base_final['Total_Visitas_Tecnicas'] = base_final['Total_Visitas_Tecnicas'].fillna(0).astype(int)
base_final['Qtd_Chamados_Defeito'] = base_final['Qtd_Chamados_Defeito'].fillna(0).astype(int)
base_final['Historico_Defeito_Principal'] = base_final['Historico_Defeito_Principal'].fillna('Nenhuma O.S. no ano')

# ordenar clientes que mais sofreram com defeitos
base_final = base_final.sort_values(by='Qtd_Chamados_Defeito', ascending=False).reset_index(drop=True)

"""**EXPORTAÇÃO E VALIDAÇÃO DOS DADOS**"""

# seleção de colunas para validação em tela
colunas_executivas = [
    'ID_Sistema', 'Nome_Cliente', 'Motivo', 'Cidade',
    'Total_Visitas_Tecnicas', 'Qtd_Chamados_Defeito', 'Historico_Defeito_Principal'
]

print("\n--- TOP 10 HISTÓRICO TÉCNICO ---")
print(base_final[colunas_executivas].head(10))

#salvar a base mestra em formato Excel
caminho_saida = './base_master_cancelamentos_abril.xlsx'
base_final.to_excel(caminho_saida, index=False)
print("\nBase de Abril gerada localmente com sucesso.")

"""# **GRÁFICOS**"""

# CONFIGURAÇÃO DA IDENTIDADE VISUAL INSTITUCIONAL

COR_PRIMARIA = '#1A365D'  # Azul Marinho profundo institucional
COR_SECUNDARIA = '#2B6CB0' # Azul de destaque para contraste
COR_TEXTO = '#2D3748'      # Cinza escuro para excelente legibilidade
COR_FUNDO_GRID = '#F7FAFC' # Cinza bem suave para o fundo do gráfico

sns.set_theme(style="whitegrid", rc={
    "axes.facecolor": COR_FUNDO_GRID,
    "grid.color": "#E2E8F0",
    "text.color": COR_TEXTO,
    "axes.labelcolor": COR_TEXTO,
    "xtick.color": COR_TEXTO,
    "ytick.color": COR_TEXTO
})
plt.rcParams['font.size'] = 11

# processamento rápido de agrupamento para validação visual
city_summary = base_final.groupby('Cidade').agg(
    Qtd_Cancelamentos=('ID_Sistema', 'count'),
    Receita_Perdida=('Valor_Plano_Num', 'sum')
).reset_index().sort_values(by='Qtd_Cancelamentos', ascending=False)

# IMPACTO FINANCEIRO E VOLUME DE CHURN POR CIDADE

cores_cidades = [COR_PRIMARIA, COR_SECUNDARIA]

fig, ax1 = plt.subplots(figsize=(9, 5.5))

sns.barplot(
    data=city_summary,
    x='Cidade',
    y='Qtd_Cancelamentos',
    palette=cores_cidades,
    hue='Cidade',
    legend=False,
    ax=ax1
)

ax1.set_title('Volume Total de Clientes Cancelados por Cidade (Abril)', fontsize=14, fontweight='bold', pad=20, color=COR_PRIMARIA)
ax1.set_xlabel('Cidade Operada', fontsize=12, fontweight='bold')
ax1.set_ylabel('Quantidade de Clientes (Churn)', fontsize=12, fontweight='bold')
ax1.set_ylim(0, city_summary['Qtd_Cancelamentos'].max() + 4)

# adicionar rótulos duplos em cima de cada barra: Quantidade de clientes + Valor perdido
for p, (_, row) in zip(ax1.patches, city_summary.iterrows()):
    h = p.get_height()
    if not np.isnan(h) and h > 0:
        texto_rotulo = f"{int(h)} Cli\n(R$ {row['Receita_Perdida']:.2f})"
        ax1.annotate(texto_rotulo, (p.get_x() + p.get_width() / 2., h + 0.5),
                    ha='center', va='bottom', fontsize=10, fontweight='bold', color=COR_TEXTO)

plt.tight_layout()
plt.show()

# RELAÇÃO ENTRE DEFEITOS TÉCNICOS HISTÓRICOS E MOTIVOS

# agrupar por motivo para somar as falhas reais encontradas em 4 meses
motivo_summary = base_final.groupby('Motivo').agg(
    Qtd_Clientes=('ID_Sistema', 'count')
).reset_index().sort_values(by='Qtd_Clientes', ascending=False)

fig, ax2 = plt.subplots(figsize=(11, 5.5))

# Barra principal (maior motivo) recebe a cor de destaque institucional
cores_motivos = [COR_PRIMARIA] + [COR_SECUNDARIA] * (len(motivo_summary) - 1)

sns.barplot(
    data=motivo_summary,
    y='Motivo',
    x='Qtd_Clientes',
    palette=cores_motivos,
    hue='Motivo',
    legend=False,
    ax=ax2
)

ax2.set_title('Distribuição de Cancelamentos por Motivo Declarado', fontsize=14, fontweight='bold', pad=20, color=COR_PRIMARIA)
ax2.set_xlabel('Quantidade Absoluta de Clientes', fontsize=12, fontweight='bold')
ax2.set_ylabel('Motivo no Sistema', fontsize=12, fontweight='bold')
ax2.set_xlim(0, motivo_summary['Qtd_Clientes'].max() + 3)

# adicionar rótulos horizontais limpos
for p in ax2.patches:
    w = p.get_width()
    if not np.isnan(w) and w > 0:
        ax2.annotate(f" {int(w)} clientes", (w, p.get_y() + p.get_height() / 2.),
                    ha='left', va='center', fontsize=10, fontweight='bold', color=COR_TEXTO)

plt.tight_layout()
plt.show()

# CONFIGURAÇÃO DE IDENTIDADE VISUAL INSTITUCIONAL

COR_MARINHO = '#1A365D'
COR_AZUL_DESTAQUE = '#2B6CB0'
COR_TEXTO = '#2D3748'
COR_FUNDO = '#F7FAFC'

sns.set_theme(style="whitegrid", rc={
    "axes.facecolor": COR_FUNDO,
    "grid.color": "#E2E8F0",
    "text.color": COR_TEXTO
})

# ENGENHARIA DE DADOS: CALCULANDO O TEMPO DE CASA (EM MESES)
# convertendo as colunas para o formato de data correto
base_final['Data_Cancelamento_DT'] = pd.to_datetime(base_final['Data Cancelamento'], format='%d/%m/%Y', errors='coerce')
base_final['Data_Ativacao_DT'] = pd.to_datetime(base_final['Data Ativação'], format='%d/%m/%Y', errors='coerce')

# calcula a diferença em dias e transforma em meses aproximados
base_final['Dias_Contrato'] = (base_final['Data_Cancelamento_DT'] - base_final['Data_Ativacao_DT']).dt.days
base_final['Meses_Contrato'] = (base_final['Dias_Contrato'] / 30.44).fillna(0).astype(int)

# categorizando o tempo de casa para o gráfico ficar executivo
def faixas_tempo(meses):
    if meses <= 3: return '0 a 3 meses (Crítico)'
    elif meses <= 6: return '4 a 6 meses'
    elif meses <= 12: return '7 a 12 meses (1 Ano)'
    elif meses <= 24: return '1 a 2 anos'
    else: return 'Mais de 2 anos (Veterano)'

base_final['Tempo_de_Casa'] = base_final['Meses_Contrato'].apply(faixas_tempo)
ordem_tempo = ['0 a 3 meses (Crítico)', '4 a 6 meses', '7 a 12 meses (1 Ano)', '1 a 2 anos', 'Mais de 2 anos (Veterano)']

# GRÁFICO 1: TEMPO DE CASA
fig, ax1 = plt.subplots(figsize=(10, 5))
sns.countplot(
    data=base_final,
    y='Tempo_de_Casa',
    order=ordem_tempo,
    palette=[COR_AZUL_DESTAQUE if 'Mais' in x or '1 a 2' in x else COR_MARINHO for x in ordem_tempo],
    hue='Tempo_de_Casa',
    legend=False,
    ax=ax1
)
ax1.set_title('Ciclo de Vida do Cliente: Quanto tempo eles duram antes do Churn?', fontsize=13, fontweight='bold', pad=15, color=COR_MARINHO)
ax1.set_xlabel('Quantidade de Clientes')
ax1.set_ylabel('Tempo de Contrato Ativo')

for p in ax1.patches:
    w = p.get_width()
    if not np.isnan(w) and w > 0:
        ax1.annotate(f" {int(w)} clie", (w, p.get_y() + p.get_height() / 2.), ha='left', va='center', fontweight='bold')

plt.tight_layout()
plt.show()

# ENGENHARIA DE DADOS: PREVISÃO / PROJEÇÃO DE PREJUÍZO ANUAL

city_finance = base_final.groupby('Cidade')['Valor_Plano_Num'].sum().reset_index()

# previsão anualizada: Perda Mensal multiplicada por 12 meses
city_finance['Prejuizo_Anual_Projetado'] = city_finance['Valor_Plano_Num'] * 12

# GRÁFICO 2: PREVISÃO ANUAL
fig, ax2 = plt.subplots(figsize=(9, 5))
sns.barplot(
    data=city_finance,
    x='Cidade',
    y='Prejuizo_Anual_Projetado',
    palette=[COR_MARINHO, COR_AZUL_DESTAQUE],
    hue='Cidade',
    legend=False,
    ax=ax2
)
ax2.set_title('Projeção e Previsão de Prejuízo Anualizado se o Churn Mantiver o Ritmo', fontsize=13, fontweight='bold', pad=15, color=COR_MARINHO)
ax2.set_xlabel('Cidade')
ax2.set_ylabel('Perda Estimada em 12 Meses (R$)')

for p, (_, row) in zip(ax2.patches, city_finance.iterrows()):
    h = p.get_height()
    if not np.isnan(h) and h > 0:
        ax2.annotate(f"Previsão de Perda Anual:\nR$ {h:.2f}", (p.get_x() + p.get_width() / 2., h/2),
                    ha='center', va='center', fontsize=11, fontweight='bold', color='white')

plt.tight_layout()
plt.show()

# CÁLCULO DO PREJUÍZO REAL (MAIO A DEZEMBRO DE 2026)

# definindo o fim do ano como dezembro de 2026
data_fim_ano = pd.to_datetime('31/12/2026', format='%d/%m/%Y')
base_final['Data_Cancelamento_DT'] = pd.to_datetime(base_final['Data Cancelamento'], format='%d/%m/%Y', errors='coerce')

# descobfrir quantos meses restavam no ano a partir do momento do cancelamento
base_final['Meses_Restantes_Ano'] = ((data_fim_ano - base_final['Data_Cancelamento_DT']).dt.days / 30.44).fillna(0).astype(int)

# mensalidade do Cliente x Quantidade de meses que ele deixará de pagar até Dezembro
base_final['Prejuizo_Real_Ate_Fim_Ano'] = base_final['Valor_Plano_Num'] * base_final['Meses_Restantes_Ano']

# agrupar por cidade para ver o impacto real acumulado no caixa
prejuizo_caixa_cidade = base_final.groupby('Cidade')['Prejuizo_Real_Ate_Fim_Ano'].sum().reset_index()

# PLOT DO GRÁFICO DE PREJUÍZO REAL NO CAIXA

fig, ax = plt.subplots(figsize=(9, 5.5))

sns.barplot(
    data=prejuizo_caixa_cidade,
    x='Cidade',
    y='Prejuizo_Real_Ate_Fim_Ano',
    palette=[COR_MARINHO, COR_AZUL_DESTAQUE],
    hue='Cidade',
    legend=False,
    ax=ax
)

ax.set_title('Dinheiro que Deixou de Entrar no Caixa até o Fim do Ano (Maio a Dez/2026)', fontsize=13, fontweight='bold', pad=20, color=COR_MARINHO)
ax.set_xlabel('Cidade', fontsize=11, fontweight='bold')
ax.set_ylabel('Total de Receita Contratual Perdida (R$)', fontsize=11, fontweight='bold')

# adicionar o valor exato que o caixa perdeu em cima das barras
for p in ax.patches:
    h = p.get_height()
    if not np.isnan(h) and h > 0:
        ax.annotate(f"Perda Real no Ano:\nR$ {h:.2f}", (p.get_x() + p.get_width() / 2., h/2),
                    ha='center', va='center', fontsize=11, fontweight='bold', color='white')

plt.tight_layout()
plt.show()

# print para ler os números rápidos
total_geral_perdido = financeiro_acumulado = prejuizo_caixa_cidade['Prejuizo_Real_Ate_Fim_Ano'].sum()
print(f"\n IMPACTO FINANCEIRO REAL NO CAIXA DA EMPRESA:")
print(f"Esse grupo de clientes que saiu em abril vai deixar um buraco de R$ {total_geral_perdido:.2f} até dezembro de 2026!")